Admin_Device/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Admin_Device.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('device_app.urls', namespace = "device_app")),
    url(r'^admin/', include(admin.site.urls)),
)

device_app/urls.py
from django.conf.urls import patterns, url
from device_app.views import inicio,register, newDevice, newApplication,devices


urlpatterns = patterns('',
	# pagina inicio y login
	url(r'^$', 'device_app.views.inicio', name='inicio'),
	# registrar usuario nuevo
	url(r'^register/$', 'device_app.views.register', name= 'register'),
	#pagina principal - muestra apps y devices
	url(r'^appsDevices/$', 'device_app.views.appsDevices', name= 'appsDevices'),
	# registrar nuevo dispositivo
	url(r'^newDevice/$', 'device_app.views.newDevice', name = 'newDevice'),
	# registrar nueva aplicacion
	url(r'^newApplication/$', 'device_app.views.newApplication', name="newApplication"),
	# mostrar dispositivos
	url(r'^devices/$', 'device_app.views.devices', name="devices"),
	# mostrar aplicaciones
	url(r'^applications/$', 'device_app.views.applications', name="applications"),
	# logout
	url(r'^logout/$', 'device_app.views.logOut', name='logout'),
	# dispositivo
	url(r'^device/id/(?P<id>\d+)/(.+)$', 'device_app.views.device' , name="device"),
	# Aplicacion
	url(r'^app/id/(?P<id>\d+)/(.+)$', 'device_app.views.app' , name="app"),
	# detalles Devices
	url(r'^detailsDevice/id/(?P<id>\d+)/(.+)$', 'device_app.views.detailsDevice' , name="detailsDevice"),
	# detalles Apps
	url(r'^detailsApps/id/(?P<id>\d+)/(.+)$', 'device_app.views.detailsApps' , name="detailsApps"),
	# instalar Apps
	url(r'^installAppInicio/$', 'device_app.views.installAppInicio' , name="installAppInicio"),
	# instalar Apps - especifica
	url(r'^installApp2/id/(?P<id>\d+)/(.+)$', 'device_app.views.installApp2' , name="installApp2"),	
	# buscar
	url(r'^buscarApp/$', 'device_app.views.buscarApp' , name="buscarApp"),
	)

device_app/models.py
from django.db import models

# Create your models here.

class Device(models.Model):
	name = models.CharField(max_length=100, unique=True)
	ip = models.CharField(max_length=12, unique=True)
	status = models.CharField(max_length=10)
	tipo = models.CharField(max_length=10)

	def __str__(self):
		return self.name


class Application(models.Model):
	name = models.CharField(max_length=100, unique=True)

	def __str__(self):
		return self.name


class DeviceApp(models.Model):
	device = models.ForeignKey(Device)
	aplication = models.ForeignKey(Application)
	status = models.CharField(max_length=10)

	def __str__(self):
		return self.device.name +' '+ self.aplication.name	

device_app/forms.py
from django import forms
from models import Device, Application, DeviceApp

TYPE_CHOICES = (
	('PC.jpg', 'PC'),
	('Cel.png', 'Celular'),
	('Tablet.jpg', 'Tableta'),
)
class NewDeviceForm(forms.Form):
	nombre = forms.CharField()
	tipo = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}), choices=TYPE_CHOICES)
	ip = forms.IntegerField()
	aplicaciones = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'form-control'}),
		queryset=Application.objects.all(), required=False)

class NewUser(forms.Form):
	nombre = forms.CharField()
	apellido = forms.CharField()
	correo = forms.EmailField()
	usuario = forms.CharField()
	contrasena = forms.CharField(widget = forms.PasswordInput())

class LogForm(forms.Form):
	usuario = forms.CharField()
	contrasena = forms.CharField(widget = forms.PasswordInput()) 

class NewAppForm(forms.Form):
	nombre = forms.CharField()

class installAppForm(forms.Form):
	dispositivo = forms.CharField()	

device_app/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template.context import RequestContext
from django.core.urlresolvers import reverse

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from models import Device, Application, DeviceApp
from forms import NewDeviceForm, NewUser, LogForm, NewAppForm, installAppForm

# Create your views here.
# ---------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------
# login
def inicio(request):
	if request.method == 'POST':
		form = LogForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data["usuario"]
			password = form.cleaned_data["contrasena"]
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					return HttpResponseRedirect(reverse('device_app:appsDevices'),request)
				else:
					return HttpResponseRedirect(reverse('device_app:inicio'))
			else:
				form = LogForm()
		    	context = {
		    	'formulario':form,
		    	'mensaje':'usuario y/o contrasena invalido'
		    	}
		    	return render_to_response('inicio.html',context,context_instance=RequestContext(request))
	else:
		form = LogForm()
    	context = {
    	'formulario':form,
    	}
    	return render_to_response('inicio.html',context,context_instance=RequestContext(request))

# ---------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------
def logOut(request):
	logout(request)
	return HttpResponseRedirect(reverse('device_app:inicio'))

# ---------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------
def register(request):
	if request.method == 'POST':
		form = NewUser(request.POST)
		if form.is_valid():
			username = form.cleaned_data["usuario"]

			# si el usuario no existe se crea
			if not User.objects.filter(username = username):
				
				password = form.cleaned_data["contrasena"]
				email = form.cleaned_data["correo"]
				first_name = form.cleaned_data["nombre"]
				last_name = form.cleaned_data["apellido"]

				user = User.objects.create_user(username, email, password)
				user.first_name = first_name
				user.last_name = last_name
				user.save()
				# toca cambiar posteriormente el retorno para que el usuario quede logeado directamente
				return HttpResponseRedirect(reverse('device_app:inicio'))
			else:
				context = {
				'formulario':form,
				'mensaje':'El Usuario ya existe'
				}
				return render_to_response('register.html',context,context_instance=RequestContext(request))
		else:
			form = NewUser()
			context = {
			'formulario':form,
			'mensaje':'Registre los datos correctamente'
			}
			return render_to_response('register.html',context,context_instance=RequestContext(request))
	else:
		form = NewUser()
		context = {
		'formulario':form,
		}
		return render_to_response('register.html',context,context_instance=RequestContext(request))

# ---------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------
@login_required(login_url='device_app:inicio')
def newDevice(request):
	if request.method == 'POST':
		form = NewDeviceForm(request.POST)
		if form.is_valid():
			
			nombre = form.cleaned_data['nombre']
			tipo = form.cleaned_data['tipo']
			ip = form.cleaned_data['ip']
			aplicacion = form.cleaned_data['aplicaciones']

			if not Device.objects.filter(name=nombre) and not Device.objects.filter(ip=ip):
				newDevice = Device(name=nombre,ip=ip,tipo=tipo,status='ON')
				newDevice.save()

				if aplicacion:
					newDeviceApp = DeviceApp(device=newDevice,aplication=aplicacion,status='ON')
					newDeviceApp.save()

				form = NewDeviceForm()
				context = {
				'formulario':form,
				'mensaje':'Dispositivo creado con exito',
				}
				return render_to_response('newDevice.html', context, context_instance=RequestContext(request))
			else:
				form = NewDeviceForm()
				context = {
				'formulario':form,
				'mensaje':'Nombre o ip de dispositivo ya existente',
				}
				return render_to_response('newDevice.html', context, context_instance=RequestContext(request))
		else:
			form = NewDeviceForm()
			context = {
			'formulario':form,
			'mensaje':'Registre los datos correctamente',
			}
			return render_to_response('newDevice.html', context, context_instance=RequestContext(request))
	else:
		form = NewDeviceForm()
		context = {
		'formulario':form,
		}
		return render_to_response('newDevice.html',context, context_instance=RequestContext(request))

# ---------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------
@login_required(login_url='device_app:inicio')
def newApplication(request):
	if request.method == 'POST':
		form = NewAppForm(request.POST)
		if form.is_valid():
			nombre = form.cleaned_data['nombre']
			nombre = nombre.lower()
			if not Application.objects.filter(name = nombre):
				newApplication = Application(name=nombre)
				newApplication.save()
			form = NewAppForm()
			context = {
			'formulario':form,
			'mensaje':'Aplicaion creada con exito',
			}
			return render_to_response('newApplication.html', context, context_instance=RequestContext(request))
	else:
		form = NewAppForm()
		context = {
		'formulario':form,
		'mensaje':'Registre los datos correctamente',
		}
		return render_to_response('newApplication.html',context,context_instance=RequestContext(request))

# ---------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------
@login_required(login_url='device_app:inicio')
def appsDevices(request):
	devices = Device.objects.all()
	applications = Application.objects.all()
	context = {
	'devices': devices,
	'applications': applications,
	'user': request.user,
	}
	return render_to_response('appsDevices.html',context)

# ---------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------
@login_required(login_url='device_app:inicio')
def devices(request):
	devices = Device.objects.all()
	context = {
	'devices': devices,
	'user': request.user,
	}
	return render_to_response('devices.html',context)

# ---------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------
@login_required(login_url='device_app:inicio')
def applications(request):
	applications = Application.objects.all()
	context = {
	'applications': applications,
	'user': request.user,
	}
	return render_to_response('applications.html',context)

# ---------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------
def device(request,id):
	dispositivo = Device.objects.filter(id=id)[0]
	aplicaciones = DeviceApp.objects.filter(device=dispositivo)
	context = {
	'device':dispositivo,
	'apps':aplicaciones,
	'user': request.user,
	}
	return render_to_response('device.html',context)

# ---------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------
def app(request,id):
	aplicacion = Application.objects.filter(id=id)[0]
	dispositivos = DeviceApp.objects.filter(aplication=aplicacion)
	context = {
	'app':aplicacion,
	'devices':dispositivos,
	'user': request.user,
	}
	return render_to_response('app.html',context)

# ---------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------
def detailsDevice(request,id):
	dispositivo = Device.objects.filter(id=id)[0]
	context = {
	'device':dispositivo,
	'user': request.user,
	}
	return render_to_response('detailsDevice.html',context)

# ---------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------
def detailsApps(request,id):
	app = Application.objects.filter(id=id)[0]
	context = {
	'app':app,
	'user': request.user,
	}
	return render_to_response('detailsApps.html',context)

# ---------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------
def buscarApp(request):
	if request.method == 'POST':
		nombre = request.POST['buscar']
		if Application.objects.filter(name__contains=nombre):

device_app/templates/applications.html
{% extends 'base.html' %}
{% block title %}Aplicaciones{% endblock %}
{%block head %}
	<link rel="stylesheet" href="/static/misEstilos/estilos2.css" />
	<link rel="stylesheet" href="/static/misEstilos/estiloBotonEstado.css" />
{%endblock%}
{% block botonIndice %}
	{% if user.is_authenticated %}
	<label class="usuario-label">{{user.username}}</label>
	<a href="{% url 'device_app:logout'%}" class="btn btn-default">
  		<span class="glyphicon glyphicon-chevron-left"></span> Salir
	</a>
	{%endif%}
	<a href="{% url 'device_app:appsDevices'%}" class="btn btn-default ">
  		<span class="glyphicon glyphicon-chevron"></span> Inicio
	</a>
{% endblock %}
{% block contenido %}
	<section class="section-register section-devices">
		<div class="container-fluid">
			<table class="table table-striped table-device">
				<thead>
				<tr>
					<th><h3>Aplicaciones</h3></th>
					<th><h3>Detalles</h3></th>
					<th><h3><a href="{% url 'device_app:newDevice'%}" class="btn btn-lg btn-primary "><span class = "glyphicon glyphicon-cloud"></span> Nueva Aplicacion</a></h3></th>
				</tr>
				</thead>
				<tbody>
				{% if applications %}
				{%for app in applications%}
				<tr>
					<td>
						<img src="/static/images/apps/{{app.name}}.jpg" class="img-circle">
						<label>{{app.name}}</label>
					</td>
					<td>
						<div class="center-td">
							<h4><a href="{% url 'device_app:detailsApps' app.id app.name %}">Detalles</a></h4>
						</div>
					</td>
					<td>
						<div class="center-td">	
							<a href="{% url 'device_app:app' app.id app.name %}" class="btn btn-primary ">Ver Aplicacion <span class="glyphicon glyphicon-chevron-right"></span></a>
						</div>
					</td>
				</tr>
				{% endfor %}
				{% endif%}
				</tbody>
				<tfoot>
				</tfoot>
			</table>
		</div>
	</section>
{% endblock %}

device_app/templates/appsDevices.html
{% extends 'base.html' %}
{% block title %}Pagina Principal{% endblock %}
{%block head %}
	<link rel="stylesheet" href="/static/misEstilos/estilos2.css" />
	<link rel="stylesheet" href="/static/misEstilos/estiloBotonEstado.css" />
{%endblock%}
{% block botonIndice %}
	{% if user.is_authenticated %}
	<a href="{% url 'device_app:installAppInicio' %}" class="btn btn-default">
  		<span class="glyphicon glyphicon-ok"></span> Instalar App
	</a>
	<label class="usuario-label">{{user.username}}</label>
	<a href="{% url 'device_app:logout'%}" class="btn btn-default">
  		<span class="glyphicon glyphicon-chevron-left"></span> Salir
	</a>
	{%endif%}
{% endblock %}
{% block contenido %}
<div>
	<div class="section-register-appsDevices" >
		<div class="span2">
			<h1><a href="{% url 'device_app:devices'%}" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-th"></span> Todos los Dispositivos</a></h1>
		</div>
		<table class="table table-striped">
			<tr><td><h1>Devices</h1></td></tr>
			<tr><td></td></tr>
		</table>
		<div class="table-device-appsDevices">						
			{% if devices %}
				<ul>
				{%for device in devices%}
					<li>
						<p><img src="/static/images/{{device.tipo}}">
						<p><label>{{device.name}}</label>
						<p><a class="boton" href="{% url 'device_app:detailsDevice' device.id device.name %}">Details</a>
					</li>
				{% endfor %}
				</ul>
			{% endif%}
		</div>
		<div class="span">
			<h1><a href="{% url 'device_app:newDevice'%}" class="btn btn-lg btn-primary "><span class = "glyphicon glyphicon-cloud"></span> Nuevo Dispositivo</a></h1>
		</div>
	</div>

	<br><br>

	<div class="section-register-appsDevices" >
		<div class="span2">
			<h1><a href="{% url 'device_app:applications'%}" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-th"></span> Todas las Aplicaciones</a></h1>
		</div>
		<table class="table table-striped">
			<td><h1>Applications</h1></td>
			<tr><td><br>
		</table>
		<div class="table-device-appsDevices">
			{% if applications %}
				<ul>
				{%for app in applications%}
					<li>
						<p><img src="/static/images/apps/{{app.name}}.jpg">
						<p><label>{{app.name}}</label>
						<p><a class="boton" href="{% url 'device_app:detailsApps' app.id app.name %}" >Details</a>
					</li>
				{% endfor %}
				</ul>
			{% endif%}
		</div>
		<div class="span">
			<a href="{% url 'device_app:newApplication'%}" class="btn btn-lg btn-primary "><span class = "glyphicon glyphicon-cloud"></span> Nueva Applicacion</a>
		</div>
	</div>
	
</div>
	


	
{% endblock %}

device_app/templates/devices.html
{% extends 'base.html' %}
{% block title %}Dispositivos{% endblock %}
{%block head %}
	<link rel="stylesheet" href="/static/misEstilos/estilos2.css" />
	<link rel="stylesheet" href="/static/misEstilos/estiloBotonEstado.css" />
{%endblock%}
{% block botonIndice %}
	{% if user.is_authenticated %}
	<label class="usuario-label">{{user.username}}</label>
	<a href="{% url 'device_app:logout'%}" class="btn btn-default">
  		<span class="glyphicon glyphicon-chevron-left"></span> Salir
	</a>
	{%endif%}
	<a href="{% url 'device_app:appsDevices'%}" class="btn btn-default ">
  		<span class="glyphicon glyphicon-chevron"></span> Inicio
	</a>
{% endblock %}
{% block contenido %}
	<section class="section-register section-devices">
		<div class="container-fluid">
			<table class="table table-striped table-device">
				<thead>
				<tr>
					<th><h3>Dispositivos</h3></th>
					<th><h3>Estado</h3></th>
					<th><h3>Detalles</h3></th>
					<th><h3><a href="{% url 'device_app:newDevice'%}" class="btn btn-lg btn-primary "><span class = "glyphicon glyphicon-cloud"></span> Nuevo Dispositivo</a></h3></th>
				</tr>
				</thead>
				<tbody>
				{% if devices %}
				{%for device in devices%}
				<tr>
					<td>
						<img src="/static/images/{{device.tipo}}" class="img-circle">
						<label>{{device.name}}</label>
					</td>
					<td>
						<div class="center-td">
							<div class="onoffswitch">
						<!-- estado del dispositivo -->
							{%ifequal device.status 'ON'%}	
						    <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" disabled="true" checked>
						    {%else%}
						    <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch" disabled="true">
						    {%endifequal%}
						<!-- fin -->
						    <label class="onoffswitch-label" for="myonoffswitch">
						        <span class="onoffswitch-inner"></span>
						        <span class="onoffswitch-switch"></span>
						    </label>
							</div>
						</div>
					</td>
					<td>
						<div class="center-td">
							<h4><a href="{% url 'device_app:detailsDevice' device.id device.name %}">Detalles</a></h4>
						</div>
					</td>
					<td>
						<div class="center-td">	
							<a href="{% url 'device_app:device' device.id device.name %}" class="btn btn-primary ">Ver dispositivo <span class="glyphicon glyphicon-chevron-right"></span></a>
						</div>
					</td>
				</tr>
				{% endfor %}
				{% endif%}
				</tbody>
				<tfoot>
				</tfoot>
			</table>
		</div>
	</section>
{% endblock %}

device_app/templates/inicio.html
{% extends 'base.html' %}
{% block title %}Inicio{% endblock %}
{% block botonIndice %}
	<a href="{% url 'device_app:register'%}" class="btn btn-default">
  		<span class="glyphicon glyphicon-chevron-left"></span> Registrarse
	</a>
{% endblock %}
{% block contenido %}
	<section>
		<div class="container log">
		    <div class="row">
		    	<div class="col-md-6">
		    		<img src="/static/images/computadores.jpg" >
		    	</div>
		        <div class="col-md-6">
		            <h1 class="titulo">Admin Application</h1>
		            <h1 class="descripcion">Estado de tus aplicaciones estes donde estes</h1>
		            <h1 class="login-title">Ingresar</h1>
		            
	                <form class="form-signin" method='POST'>{% csrf_token %}
		                <input type="text" class="form-control" id="id_usuario" name="usuario" placeholder="Usuario" required autofocus>
		                <input type="password" class="form-control" id="id_contrasena" name="contrasena" placeholder="Contraseña" required>
		                <button class="btn btn-lg btn-primary btn-block" type="submit">
		                    Entrar
		                </button>
	                </form>
	                <!-- mejorar apriencia de mensaje -->
	                <label>{{mensaje}}<label>
		        </div>
		    </div>
		</div>		
	</section>
{% endblock %}

device_app/templates/installApp.html
{% extends 'base.html' %}
{% block title %}Pagina Principal{% endblock %}
{%block head %}
	<link rel="stylesheet" href="/static/misEstilos/estilos2.css" />
	<link rel="stylesheet" href="/static/misEstilos/estiloBotonEstado.css" />
{%endblock%}
{% block botonIndice %}
	{% if user.is_authenticated %}
	<label class="usuario-label">{{user.username}}</label>
	<a href="{% url 'device_app:logout'%}" class="btn btn-default">
  		<span class="glyphicon glyphicon-chevron-left"></span> Salir
	</a>
	<a href="{% url 'device_app:appsDevices'%}" class="btn btn-default ">
  		<span class="glyphicon glyphicon-chevron"></span> Inicio
	</a>
	{%endif%}
{% endblock %}
{% block contenido%}
<div class="section-register-appsDevices">
	<br><br><br>	
	<table class="table table-striped">
		<td><h1>Applications</h1></td>
		<tr><h4>{{mensaje}}</h4></tr>
		<tr>
			<form action="{% url 'device_app:buscarApp' %}" method='POST'>{% csrf_token %}
				<td>
					<div class="buscar">
	    				<div class="input-group">
	      					<input type="text" name="buscar" class="form-control">
	      					<span class="input-group-btn">
	      						<button type="submit" class="btn btn-primary ">
						  			<span class="glyphicon glyphicon-search"></span> Buscar
								</button>	
	      					</span>	      		
	    				</div>
	  				</div>
				</td>
			</form>
		</tr>
	<br>
	</table>
	<div class="table-device-appsDevices apss-install">
		{% if applications %}
		<ul>
			{%for app in applications%}
				<li><a href="{% url 'device_app:installApp2' app.id app.name %}" >
					<p><img src="/static/images/apps/{{app.name}}.jpg">
					<p><h3><label>{{app.name}}</label></h3>
					</a>
				</li>
			{% endfor %}
			</ul>
		{% endif%}
	</div>
	<div class="span">
		<a href="{% url 'device_app:newApplication'%}" class="btn btn-lg btn-primary "><span class = "glyphicon glyphicon-cloud"></span> Nueva Applicacion</a>
	</div>
</div>
{% endblock %}

device_app/templates/newDevice.html
{% extends 'base.html' %}
{% block title %}Nuevo Dispositivo{% endblock %}
{%block head %}
	<link rel="stylesheet" href="/static/misEstilos/estilos2.css" />
{%endblock%}
{% block botonIndice %}
	{% if user.is_authenticated %}
	<label class="usuario-label">{{user.username}}</label>
	<a href="{% url 'device_app:logout'%}" class="btn btn-default">
  		<span class="glyphicon glyphicon-chevron-left"></span> Salir
	</a>
	{%endif%}
	<a href="{% url 'device_app:appsDevices'%}" class="btn btn-default ">
  		<span class="glyphicon glyphicon-chevron"></span> Inicio
	</a>
{% endblock %}
{% block contenido %}
	<section class="section-register">
		<div class=	"container-fluid">
			<div class="row">
				<h1 class="titulo titulo-register" >Nuevo Dispositivo</h1>
				<form class="form-horizontal form-register" role="form" method='POST'>{% csrf_token %}
					<div class="form-group">
						<label for="inputName" class="col-sm-4 control-label">Nombre:</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="id_nombre" name="nombre" placeholder="Nombre" required>
						</div>
					</div>
					<div class="form-group">
						<label for="inputType" class="col-sm-4 control-label">Tipo:</label>
						<div class="col-sm-8">
							{{formulario.tipo}}
						</div>
					</div>
					<div class="form-group">
						<label for="inputIP" class="col-sm-4 control-label">Dirección IP:</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="id_ip" name ="ip" placeholder="Dirección IP" required>
						</div>
					</div>
					<div class="form-group">
						<label for="inputApp" class="col-sm-4 control-label">Instalar aplicación:</label>
						<div class="col-sm-8">
							{{formulario.aplicaciones}}
						</div>
					</div>
					<button type="submit" class="btn btn-lg btn-primary btn-block">Enviar</button>
				</form>
				<label>{{mensaje}}</label>
			</div>
		</div>
	</section>
{% endblock %}

device_app/templates/register.html
{% extends 'base.html' %}
{% block title %}Nuevo Usuario{% endblock %}
{%block head %}
	<link rel="stylesheet" href="/static/misEstilos/estilos2.css" />
{%endblock%}
{% block botonIndice %}
	<a href="{% url 'device_app:inicio' %}" class="btn btn-default">
  		<span class="glyphicon glyphicon-chevron-left"></span> Cancelar
	</a>
{% endblock %}
{% block contenido %}
	<section class="section-register">
		<div class=	"container-fluid">
			<div class="row">
				<h1 class="titulo titulo-register" >Nuevo Usuario</h1>
				<form class="form-horizontal form-register" role="form" method='POST'>{% csrf_token %}
					<div class="form-group">
						<label for="id_nombre" class="col-sm-2 control-label">Nombre:</label>
						<div class="col-sm-10">
						<input type="text" class="form-control" id="id_nombre" name="nombre" placeholder="Nombre" required>
						</div>
					</div>
					<div class="form-group">
						<label for="id_apellido" class="col-sm-2 control-label">Apellido:</label>
						<div class="col-sm-10">
						<input type="text" class="form-control" id="id_apellido" name="apellido" placeholder="Apellido" required>
						</div>
					</div>
					<div class="form-group">
						<label for="id_correo" class="col-sm-2 control-label">Correo:</label>
						<div class="col-sm-10">
						<input type="email" class="form-control" id="id_correo" name="correo" placeholder="Correo electrónico" required>
						</div>
					</div>
					<div class="form-group">
						<label for="id_usuario" class="col-sm-2 control-label">Usuario:</label>
						<div class="col-sm-10">
						<input type="text" class="form-control" id="id_usuario" name="usuario" placeholder="Nombre de usuario" required>
						</div>
					</div>
					<div class="form-group">
						<label for="id_contrasena" class="col-sm-2 control-label">Contraseña:</label>
					  	<div class="col-sm-10">
					  	<input type="password" class="form-control" id="id_contrasena" name="contrasena" placeholder="Contraseña" required>
					  </div>
					</div>
						  <button type="submit" class="btn btn-lg btn-primary btn-block">Enviar</button>
				</form>
				<!-- mejorar apriencia de mensaje -->
				<label>{{mensaje}}<label>
			</div>
		</div>
	</section>
{% endblock %}